export const listData = [
    {
      id: 1,
      title: `"Ao no Sumika" by Kamiyama Yoh`,
      img: "https://i.postimg.cc/cLgCwqVp/Ao-No-Sumika.jpg",
      type: "music",
      rating: 4.9,
      reviews: 3000,
      stock: 7,
      price: 12.99,
    },
    {
      id: 2,
      title: `"Going On" by Victorians`,
      img: "https://i.postimg.cc/FHMRxWv7/GoingOn.jpg",
      type: "music",
      rating: 4.5,
      reviews: 5000,
      stock: 1000,
      price: 20.99,
    },
    {
      id: 3,
      title: `"How to Eat Life" by Eve`,
      img: "https://i.postimg.cc/ZnR5VXMz/290009114-570207314706797-8964377742502211485-n.jpg",
      type: "music",
      rating: 2.5,
      reviews: 344,
      stock: 34,
      price: 12.99,
    },
    {
      id: 4,
      title: `"Demon Dance Tokyo" Kamiyama Yoh`,
      img: "https://i.postimg.cc/VL2kWG92/291498510-398676722232454-3361050522912371738-n.png",
      type: "music",
      rating: 4.0,
      reviews: 210,
      stock: 11,
      price: 5.99,
    },
    {
      id: 5,
      title: `"Mabel" by Eve`,
      img: "https://i.postimg.cc/tJMCfDKZ/Capture.jpg",
      type: "music",
      rating: 4.5,
      reviews: 5000,
      stock: 2,
      price: 5.99,
    },
    {
      id: 6,
      title: "Place Holder 1",
      img: "https://i.postimg.cc/G3Y7p97Y/placeholder.jpg",
      type: "music",
      rating: 4.5,
      reviews: 5000,
      stock: 2,
      price: 12.99,
    },
    {
      id: 7,
      title: "Place Holder 2",
      img: "https://i.postimg.cc/G3Y7p97Y/placeholder.jpg",
      type: "music",
      rating: 4.5,
      reviews: 5000,
      stock: 2,
      price: 12.99,
    },
    {
      id: 8,
      title: "Place Holder 3",
      img: "https://i.postimg.cc/G3Y7p97Y/placeholder.jpg",
      type: "music",
      rating: 4.5,
      reviews: 5000,
      stock: 2,
      price: 12.99,
    },
    {
      id: 9,
      title: "Place Holder 4",
      img: "https://i.postimg.cc/G3Y7p97Y/placeholder.jpg",
      type: "food",
      rating: 4.5,
      reviews: 5000,
      stock: 2,
      price: 15.99,
    },
    {
      id: 10,
      title: "Place Holder 5",
      img: "https://i.postimg.cc/G3Y7p97Y/placeholder.jpg",
      type: "antiques",
      rating: 4.5,
      reviews: 5000,
      stock: 2,
      price: 56.99,
    },
    {
      id: 11,
      title: "Place Holder 6",
      img: "https://i.postimg.cc/G3Y7p97Y/placeholder.jpg",
      type: "electronics",
      rating: 4.5,
      reviews: 5000,
      stock: 2,
      price: 1.99,
    },
    {
      id: 12,
      title: "Place Holder 7",
      img: "https://i.postimg.cc/G3Y7p97Y/placeholder.jpg",
      type: "electronics",
      rating: 4.5,
      reviews: 5000,
      stock: 2,
      price: 6.99,
    },
    {
      id: 13,
      title: "Place Holder 8",
      img: "https://i.postimg.cc/G3Y7p97Y/placeholder.jpg",
      type: "antiques",
      rating: 4.5,
      reviews: 5000,
      stock: 2,
      price: 4.99,
    },
    {
      id: 14,
      title: "Place Holder 9",
      img: "https://i.postimg.cc/G3Y7p97Y/placeholder.jpg",
      type: "antiques",
      rating: 4.5,
      reviews: 5000,
      stock: 2,
      price: 1.99,
    },
    {
      id: 15,
      title: "Place Holder 10",
      img: "https://i.postimg.cc/G3Y7p97Y/placeholder.jpg",
      type: "food",
      rating: 4.5,
      reviews: 5000,
      stock: 2,
      price: 5.99,
    },
    {
      id: 16,
      title: "Place Holder 11",
      img: "https://i.postimg.cc/G3Y7p97Y/placeholder.jpg",
      type: "food",
      rating: 4.5,
      reviews: 5000,
      stock: 2,
      price: 2.99,
    },
    
    
  ];
  
  export const singlePostData = [
    {
    id: 1,
    title: `'Ao no Sumika' Kamiyama Yoh physical Full Album`,
    images: [
      "https://i.postimg.cc/cLgCwqVp/Ao-No-Sumika.jpg",
      "https://i.postimg.cc/26kSw6RT/Yoh-Kamiyama-OSusume-Radio-Beat.jpg",
      "https://i.postimg.cc/xdydMm7c/hqdefault-upscaled.jpg",
      "https://i.postimg.cc/50sNkVfJ/yohkamiyama.jpg",
    ],
    artist: 'Kamiyama Yoh',
    type: "music",
    rating: 4.9,
    reviews: 3000,
    stock: 7,
    price: 12.99,
    mainDescription: `Physical Album collection of Yoh Kamiyama's hit album 'Ao no Sumika' including hit songs: 'Endroll' and 'Ao no Sumika'.`,
    subDescription: `Dive into the profound emotional landscape of Yoh Kamiyama's celebrated album, "Ao no Sumika," where each track unfolds a narrative of grief and the eventual path to acceptance. Featuring poignant hits like "Endroll" and the titular track "Ao no Sumika," this collection encapsulates the artist's exploration of human emotions in a raw and heartfelt manner.
    The album is crafted with meticulous attention to detail, ensuring every note resonates deeply with the listener's journey. Whether you're seeking solace or simply appreciating the artistry, Yoh Kamiyama's music offers a cathartic experience that transcends mere listening.
    Embrace the themes of resilience and growth woven into each song. Own a piece of musical storytelling that speaks directly to the heart and soul.`,
  },
  {
    id: 2,
    title: `'Going On' Victorians physical Full Album`,
    images: [
      "https://i.postimg.cc/FHMRxWv7/GoingOn.jpg",
      "https://i.postimg.cc/5yCw28d0/ad.png",
      "https://i.postimg.cc/26JQY2tM/290930584-1021907678495367-5533369136074405746-n.jpg",
      "https://i.postimg.cc/Bvm5YqBq/287025069-3291027284474839-5629358983001132573-n.jpg",
    ],
    artist: 'Victorians',
    type: "music",
    rating: 4.5,
    reviews: 5000,
    stock: 1000,
    price: 20.99,
    mainDescription: `Physical Album collection of Victorians's hit album 'Going On' including hit songs: 'Going On' and 'Last Dance'.`,
    subDescription: `Dive into the profound emotional landscape of Victorians's celebrated album, "Ao no Sumika," where each track unfolds a narrative of grief and the eventual path to acceptance. Featuring poignant hits like "Endroll" and the titular track "Ao no Sumika," this collection encapsulates the artist's exploration of human emotions in a raw and heartfelt manner.
    The album is crafted with meticulous attention to detail, ensuring every note resonates deeply with the listener's journey. Whether you're seeking solace or simply appreciating the artistry, Victorians's music offers a cathartic experience that transcends mere listening.
    Embrace the themes of resilience and growth woven into each song. Own a piece of musical storytelling that speaks directly to the heart and soul.`,
  }


];
  
  export const userData = [
    {
    id: 1,
    name: "Kamiyama Yoh",
    img: "https://i.postimg.cc/tT6GFG7D/yoh-removebg-preview.png",
    link:`https://www.yohkamiyama.com/`,
   },
   {
    id: 2,
    name: "Victorians",
    img: "https://i.postimg.cc/V677CqVW/165115289-499163391448448-7290380364673764155-n-1.png",
    link: "https://portfolio-b9eb3.web.app/",
   }
];

export const loginData = [
  {
    userName:"John Adam",
    email: "JAdams@gmail.com",
    password:`123456789`,
 },
];